### PR TITLE
Send Airflow alerts to slack

### PR DESCRIPTION
**Pull request by sjmiller609**
Closes https://github.com/astronomer/issues/issues/505

This will send Airflow alerts to the same slack channel as the other alerts. I think this is fine because pager duty will still only alert for the platform alerts, and there is no reason for customer success to not be aware of a platform-level alert.

### CODE REVIEW

**Comment by schnie** [comment]
@sjmiller609 I'm wondering if we need a tweak to our helm charts, or maybe we duplicate the houston receiver block up at the terraform level.

https://github.com/astronomer/helm.astronomer.io/blob/master/charts/alertmanager/templates/alertmanager-configmap.yaml#L25-L28

This makes me think that if we override one, that it'll skip forwarding these to houston, and customers won't get the emails.

We could alter this logic, or also specify the houston one in our list here. What do you think?

**Comment by sjmiller609** [comment]
hold on, there is something blocking the pipeline right now

**Comment by schnie** [comment]
What happened here? This would work right?

**Comment by sjmiller609** [comment]
pipeline is blocked by the tiller thing. that's what I'm troubleshooting right now. I do think this PR looks fine, but there is a merge conflict because I'm modifying the same file here as where I'm troubleshooting the tiller situation.

**Comment by sjmiller609** [comment]
we can merge it if we want, but it just won't deploy yet

**Comment by schnie** [comment]
Whatever is easiest for you works for me

**Pull request merged**
